// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://white-desert.com/
// Generated: 2026-08-30T11:06:00.897Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#1f2a44' | '#ffffff' | '#000000' | '#535353' | '#f3f1ec' | '#ff7e15' | '#6af0ff' | '#090b10' | '#e9e7e1' | '#c0c0c0';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter Tight' | 'Arial' | 'Times New Roman' | 'Cardinal Classic Long' | 'Oswald';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600';

export type SpacingToken = '4px' | '21px' | '24px' | '36px' | '39px' | '53px' | '58px' | '71px' | '89px' | '111px' | '124px' | '142px' | '178px' | '227px' | '284px';

export type RadiusToken = '2px' | '5px' | '50px' | '100px';

export type DurationToken = '300ms' | '450ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
